version: '3.1'

networks:
  transcendence:
    driver: bridge

services:
  nestjs-app:
    build: ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    networks:
      - transcendence
  
  nextjs-app:
    build: ./frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    networks:
      - transcendence
    command: npm start

  database:
    image: postgres
    environment:
      POSTGRES_USER: yeongo
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
    networks:
      - transcendence

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com" 
      PGADMIN_DEFAULT_PASSWORD: "admin"  
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - transcendence

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - transcendence
